# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5f190893fec9df1ff978dffafc52c2f"
application_url = "https://blogcta.orustudio.com/"
embedded = true
name = "cafeplanta-cta"
handle = "cafeplanta-cta"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blogcta.orustudio.com/auth/callback",
  "https://blogcta.orustudio.com/auth/shopify/callback",
  "https://blogcta.orustudio.com/api/auth/callback"
]

[pos]
embedded = false
