# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc69044270e65a6f15dfefb9fca0a4e6"
application_url = "https://coins-starter-cells-atom.trycloudflare.com"
embedded = true
name = "marketing-cta"
handle = "marketing-cta"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://coins-starter-cells-atom.trycloudflare.com/auth/callback",
  "https://coins-starter-cells-atom.trycloudflare.com/auth/shopify/callback",
  "https://coins-starter-cells-atom.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
